#!/bin/sh

regex='@optusnet\.com.au$'
email=$GIT_AUTHOR_EMAIL

if [[ $email =~ $regex ]];
then
    echo Your $email satifies Git policy
    exit 0
else
    echo Your $email does not satifies Git policy
    exit 1
fi
   
